/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

public class EvenFibonacci
{
    public static void main(String args[]) {
        int sum = 0, fibPP = 1, fibP = 1, fib = fibP + fibPP;
        
        while(fib <= 4000000) {
            if(fib % 2 == 0)
                sum += fib;
            fibPP = fibP;
            fibP = fib;
            fib = fibP + fibPP;
            //System.out.println(fib);
        } //end while
        System.out.println("The sum of the even Fibonacci numbers <= 4,000,000 is " + sum);
    } //end main
}
